### ISSUE TITLE
Weird export result

### ISSUE THREAD

**Issue by Charley-xiao** [nerfstudio-project/nerfstudio#3581]
I trained on the default dataset `poster` and obtained a psnr of ~20, which is not really bad. But when I exported the mesh, it looks weird:

![Image](https://github.com/user-attachments/assets/28d2392e-c33d-450d-9cf0-9d356778b871)

I tried adjusting bounding box, but it didn't really work.

Here's my command:

```
ns-export poisson --load-config outputs/poster/nerfacto/2025-01-26_000037/config.yml --output-dir exports/mesh_v4/ --target-num-faces 50000 --num-pixels-per-side 2048 --normal-method open3d --num-points 1000000 --remove-outliers True --use-bounding-box True --bounding-box-min -0.35 -0.25 -0.25 --bounding-box-max 0.15 0.25 0.25
```

Here's a screenshot from nerfstudio:

![Image](https://github.com/user-attachments/assets/e3e90452-aa11-44fe-94b1-d7565a253917)

**Comment by Charley-xiao** [comment]
> I experienced the same issue. Did you manage to solve it? I downgraded nerfstudio to version 1.0 (pip install nerfstudio==1.0) and COLMAP to version 3.8 (conda install colmap==3.8). After re-running ns-process and ns-train, the ns-export poisson command worked correctly.

Yes, downgrading works. I think they're still working on fixing the export result in the newest version of nerfstudio.

**Comment by AntonioMacaronio** [comment]
Does this issue still persist with the latest main version of nerfstudio? I've made a fix to the export result on the `main` of nerfstudio

**Comment by Toernblom** [comment]
> Does this issue still persist with the latest main version of nerfstudio? I've made a fix to the export result on the `main` of nerfstudio

I installed nerfstudio for the first time today through pip and got the same result as above. Do i need to build from source to get that latest version?

**Comment by AntonioMacaronio** [comment]
@Toernblom Sorry for the confusion, but I believe the current fix to this is located [here](https://github.com/nerfstudio-project/nerfstudio/pull/3591). The weird export result is due to a naming error with the config variables, so you'd have to check out the latest commit in that PR and build that with `pip install -e .` I believe that should resolve the error in this thread

**Comment by HeaIn** [comment]
As mentioned in the PR, try using obb_center, obb_rotation, obb_scale parameters instead.
For example:
```
ns-export poisson --load-config outputs/poster/nerfacto/2025-01-26_000037/config.yml --output-dir exports/mesh_v4/ --target-num-faces 50000 --num-pixels-per-side 2048 --normal-method open3d --num-points 1000000 --remove-outliers True --obb_center 0 0 0 --obb_rotation 0 0 0 --obb_scale 1.0 1.0 1.0
```

Training ```poster``` dataset with ```nerfacto``` and exporting mesh with the command above will look like this. 

![Image](https://github.com/user-attachments/assets/7769a342-5a36-4de0-9c57-944366fc2512)

**Comment by gaoyuqiang** [comment]
This issue still persist with the latest main version of nerfstudio.  
can anyone help me? I’ve already spent a lot of time trying to solve this issue. But It still doesn't work, even after I downgraded to version 1.0.

**Comment by HeaIn** [comment]
> This issue still persist with the latest main version of nerfstudio. can anyone help me? I’ve already spent a lot of time trying to solve this issue. But It still doesn't work, even after I downgraded to version 1.0.

Can you share the command you used to run the code?

**Comment by gaoyuqiang** [comment]
> > This issue still persist with the latest main version of nerfstudio. can anyone help me? I’ve already spent a lot of time trying to solve this issue. But It still doesn't work, even after I downgraded to version 1.0.
> 
> Can you share the command you used to run the code?

The training dataset is my own data.

Now my nerfsutdio is version 1.0 (colmap 3.8).
train command:
`ns-train nerfacto --pipeline.model.predict-normals True --data /root/autodl-tmp/out4`
export mesh command:
`ns-export poisson --load-config outputs/out4/nerfacto/2025-05-09_151502/config.yml --output-dir exports/mesh2/ --target-num-faces 50000 --num-pixels-per-side 2048 --num-points 1000000 --remove-outliers True --normal-method open3d --use_bounding_box False --obb_center 0.0000000000 0.0000000000 0.0000000000 --obb_rotation 0.0000000000 0.0000000000 0.0000000000 --obb_scale 1.0000000000 1.0000000000 1.0000000000`

If nerfsutdio is version 1.1.5 (colmap 3.8).
train command:
`ns-train nerfacto --pipeline.model.predict-normals True --data /root/autodl-tmp/out2`
export mesh command:
`ns-export poisson --load-config outputs/out2/nerfacto/2025-04-24_170555/config.yml --output-dir outputs/result6 --target-num-faces 15000 --num-pixels-per-side 2048 --num-points 250000 --remove-outliers True --normal-method open3d --obb_center -0.2400000000 -0.4400000000 -0.5300000000 --obb_rotation 0.0000000000 -0.0000000000 -0.3778622040 --obb_scale 0.7400000095 1.1299999952 1.2999999523
`
Whether it's Nerfstudio 1.0 or 1.1.5（install from lastest code) , neither of them works.
What should I do?

<img width="1417" alt="Image" src="https://github.com/user-attachments/assets/090cad8c-33a7-4cce-bc81-93f7f95e055a" />

<img width="974" alt="Image" src="https://github.com/user-attachments/assets/7ed03fbb-192a-4411-b34f-72899df1fd98" />

**Comment by gaoyuqiang** [comment]
The problem is still exist. Who can help me?

**Comment by gaoyuqiang** [comment]
ns-process-data video --data /root/autodl-fs/input.mov --output-dir outputs/data10 --num-frames-target 220
ns-train nerfacto --pipeline.model.predict-normals True --data outputs/data10
ns-export poisson --load-config outputs/data10/nerfacto/2025-08-06_173011/config.yml  --output-dir outputs/data10

**Comment by gaoyuqiang** [comment]
@HeaIn can you help me ?

**Comment by mariapatni** [comment]
I am also having this issue. I've tried reinstalling the latest version of nerfstudio and reverting to older versions but still having trouble. @HeaIn @gaoyuqiang @AntonioMacaronio has anyone solved this problem?

**Comment by HeaIn** [comment]
@mariapatni Please refer to Issue #3701. The solution and detailed parameters are described there.
